from tkinter import *
from P import *

zz = 0
pp = 0
qq = 0
nn = 0

#interface_by_Anton_Muraveoe_1308

class Window:
    def __init__(self, wight, height, title="ffr", resizable=(True, True), icon=None):
        self.root = Tk()
        self.root.title(title)
        self.root.geometry(f"{wight}x{height}+350+50")
        self.root.resizable(resizable[0], resizable[1])
        if icon:
            self.root.iconbitmap(icon)

        self.entryZ1 = Entry(self.root, font="Arial 50")
        self.entryZ2 = Entry(self.root, font="Arial 50")
        self.entryN1 = Entry(self.root, font="Arial 50")
        self.entryN2 = Entry(self.root, font="Arial 50")
        self.entryP1 = Entry(self.root, font="Arial 50")
        self.entryP2 = Entry(self.root, font="Arial 50")
        self.entryQ1 = Entry(self.root, font="Arial 50")
        self.entryQ2 = Entry(self.root, font="Arial 50")
        self.entryk = Entry(self.root, font="Arial 50")
        self.l1 = Label(self.root, text='', width=90, bg="#b2ec5d", relief=FLAT, wraplength=400, font="Arial 50")
        self.buttonREZ = Button(self.root, text="Показать результат", width=90, height=1, bg="#b2ec5d",  command=self.zoutput, font="Impact 20")
        self.buttonBA = Button(self.root, text="Вернуться на главную", width=90, height=1, bg="#ff0000",  command=self.draw_widgets, font="Impact 20")
        self.buttonN = Button(self.root, text="Натуральные числа с нулем", width=90, height=3, bg="#7fc7ff",  command=self.get_algN, font="Arial 30")
        self.buttonZ = Button(self.root, text="Целые числа", width=90, height=3, command=self.get_algZ, bg="#90ee90", font="Arial 30")
        self.buttonQ = Button(self.root, text="Рациональные числа\n (форма ввода дроби: a/b)", width=90, height=3, bg="#ffffe0", command=self.get_algQ, font="Arial 30")
        self.buttonP = Button(self.root, text="Многочлен\n с рациональными коэффициентами\n (форма ввода: рац. коэф. через пробел)", width=90, height=3, bg="#ff7e93", command=self.get_algP, font="Arial 30")
        self.buttonN_1 = Button(self.root, text="Сравнение натуральных чисел", width=100, height=2, bg="#7fc7ff", command=self.innumN1, font="Arial 10")
        self.buttonN_2 = Button(self.root, text="Проверка на ноль", width=100, height=2, bg="#7fc7ff", command=self.innumN2, font="Arial 10")
        self.buttonN_3 = Button(self.root, text="Добавление 1 к натуральному числу", width=100, height=2, bg="#7fc7ff", command=self.innumN3, font="Arial 10")
        self.buttonN_4 = Button(self.root, text="Сложение натуральных чисел", width=100, height=2, bg="#7fc7ff", command=self.innumN4, font="Arial 10")
        self.buttonN_5 = Button(self.root, text="Вычитание из первого большего натурального числа второго меньшего или равного", width=100, height=2, bg="#7fc7ff", command=self.innumN5, font="Arial 10")
        self.buttonN_6 = Button(self.root,text="Умножение натурального числа на цифру", width=100, height=2, bg="#7fc7ff", command=self.innumN6, font="Arial 10")
        self.buttonN_7 = Button(self.root, text="Умножение натурального числа на 10^k", width=100, height=2, bg="#7fc7ff", command=self.innumN7, font="Arial 10")
        self.buttonN_8 = Button(self.root, text="Умножение натуральных чисел", width=100, height=2, bg="#7fc7ff", command=self.innumN8,  font="Arial 10")
        self.buttonN_9 = Button(self.root, text="Вычитание из натурального другого натурального, умноженного на цифру для случая с неотрицательным результатом", width=100, height=2, bg="#7fc7ff", command=self.innumN9, font="Arial 10")
        self.buttonN_10 = Button(self.root, text="Вычисление первой цифры деления большего натурального на меньшее, домноженное на 10^k,где k - номер позиции этой цифры\n(номер считается с нуля)", width=100, height=2, bg="#7fc7ff", command=self.innumN10, font="Arial 10")
        self.buttonN_11 = Button(self.root, text="Частное от деления большего натурального числа на меньшее или равное натуральное с остатком\n(делитель отличен от нуля)", width=100, height=2, bg="#7fc7ff", command=self.innumN11, font="Arial 10")
        self.buttonN_12 = Button(self.root, text="Остаток от деления большего натурального числа на меньшее или равное натуральное с остатком\n(делитель отличен от нуля)", width=100, height=2, bg="#7fc7ff", command=self.innumN12, font="Arial 10")
        self.buttonN_13 = Button(self.root, text="НОД натуральных чисел", width=100, height=2, bg="#7fc7ff", command=self.innumN13, font="Arial 10")
        self.buttonN_14 = Button(self.root, text="НОК натуральных чисел", width=100, height=2, bg="#7fc7ff", command=self.innumN14, font="Arial 10")
        self.buttonZ_1 = Button(self.root, text="Абсолютная величина числа, результат - натуральное", width=100, height=2, bg="#90ee90", command=self.innumZ1, font="Arial 10")
        self.buttonZ_2 = Button(self.root, text="Определение положительности числа\n (2 - положительное, 0 — равное нулю, 1 - отрицательное)", width=100, height=2, bg="#90ee90", command=self.innumZ2, font="Arial 10")
        self.buttonZ_3 = Button(self.root, text="Умножение целого на (-1)", width=100, height=2, bg="#90ee90", command=self.innumZ3, font="Arial 10")
        self.buttonZ_4 = Button(self.root, text="Сложение целых чисел", width=100, height=2, bg="#90ee90", command=self.innumZ4,  font="Arial 10")
        self.buttonZ_5 = Button(self.root, text="Вычитание целых чисел", width=100, height=2, bg="#90ee90", command=self.innumZ5, font="Arial 10")
        self.buttonZ_6 = Button(self.root, text="Умножение целых чисел", width=100, height=2, bg="#90ee90", command=self.innumZ6, font="Arial 10")
        self.buttonZ_7 = Button(self.root, text="Частное от деления целого на целое\n (делитель отличен от нуля)", width=100, height=2, bg="#90ee90", command=self.innumZ7, font="Arial 10")
        self.buttonZ_8 = Button(self.root, text="Остаток от деления целого на целое\n (делитель отличен от нуля)", width=100, height=2, bg="#90ee90", command=self.innumZ8,  font="Arial 10")
        self.buttonQ_1 = Button(self.root, text="Сокращение дроби", width=100, height=2, bg="#ffffe0", command=self.innumQ1,font="Arial 10")
        self.buttonQ_2 = Button(self.root, text="Проверка на целое, если рациональное число является целым, то «да», иначе «нет»",  width=100, height=2, bg="#ffffe0", command=self.innumQ2,font="Arial 10")
        self.buttonQ_3 = Button(self.root, text="Сложение дробей", width=100, height=2, bg="#ffffe0",command=self.innumQ3, font="Arial 10")
        self.buttonQ_4 = Button(self.root, text="Вычитание дробей", width=100, height=2, bg="#ffffe0",command=self.innumQ4, font="Arial 10")
        self.buttonQ_5 = Button(self.root, text="Умножение дробей", width=100, height=2, bg="#ffffe0",command=self.innumQ5, font="Arial 10")
        self.buttonQ_6 = Button(self.root, text="Деление дробей\n (делитель отличен от нуля)", width=100, height=2, bg="#ffffe0",command=self.innumQ6, font="Arial 10")
        self.buttonP_1 = Button(self.root, text="Сложение многочленов", width=100, height=2, bg="#ff7e93",command=self.innumP1, font="Arial 10")
        self.buttonP_2 = Button(self.root, text="Вычитание многочленов", width=100, height=2, bg="#ff7e93",command=self.innumP2, font="Arial 10")
        self.buttonP_3 = Button(self.root, text="Умножение многочлена на рациональное число", width=100, height=2, bg="#ff7e93",command=self.innumP3, font="Arial 10")
        self.buttonP_4 = Button(self.root, text="Умножение многочлена на x^k", width=100, height=2, bg="#ff7e93",command=self.innumP4, font="Arial 10")
        self.buttonP_5 = Button(self.root, text="Старший коэффициент многочлена", width=100, height=2, bg="#ff7e93",command=self.innumP5, font="Arial 10")
        self.buttonP_6 = Button(self.root, text="Степень многочлена", width=100, height=2,  bg="#ff7e93",command=self.innumP6, font="Arial 10")
        self.buttonP_7 = Button(self.root, text="Вынесение из многочлена НОК знаменателей коэффициентов и НОД числителей", width=100, height=2, bg="#ff7e93",command=self.innumP7, font="Arial 10")
        self.buttonP_8 = Button(self.root, text="Умножение многочленов", width=100, height=2, bg="#ff7e93",command=self.innumP8, font="Arial 10")
        self.buttonP_9 = Button(self.root, text="Частное от деления многочлена на многочлен при делении с остатком", width=100, height=2, bg="#ff7e93",command=self.innumP9, font="Arial 10")
        self.buttonP_10 = Button(self.root, text="Остаток от деления многочлена на многочлен при делении с остатком", width=100, height=2, bg="#ff7e93",command=self.innumP10, font="Arial 10")
        self.buttonP_11 = Button(self.root, text="НОД многочленов", width=100, height=2, bg="#ff7e93",command=self.innumP11, font="Arial 10")
        self.buttonP_12 = Button(self.root, text="Производная многочлена", width=100, height=2, bg="#ff7e93",command=self.innumP12, font="Arial 10")
        self.buttonP_13 = Button(self.root, text="Преобразование многочлена — кратные корни в простые", width=100, height=2, bg="#ff7e93",command=self.innumP13, font="Arial 10")



    def run(self):
        self.draw_widgets()
        self.root.mainloop()



    def draw_widgets(self):
        global pp, qq, nn, zz
        pp = 0
        qq = 0
        nn = 0
        zz = 0
        self.l1.forget()
        self.entryZ1.delete(0, 'end')
        self.entryZ2.delete(0, 'end')
        self.entryN1.delete(0, 'end')
        self.entryN2.delete(0, 'end')
        self.entryP1.delete(0, 'end')
        self.entryP2.delete(0, 'end')
        self.entryQ1.delete(0, 'end')
        self.entryQ2.delete(0, 'end')
        self.entryk.delete(0, 'end')
        self.entryP1.forget()
        self.entryP2.forget()
        self.entryQ1.forget()
        self.entryQ2.forget()
        self.entryZ1.forget()
        self.entryZ2.forget()
        self.entryN1.forget()
        self.entryN2.forget()
        self.entryk.forget()
        self.buttonREZ.forget()
        self.buttonBA.forget()
        self.buttonN_1.forget()
        self.buttonN_2.forget()
        self.buttonN_3.forget()
        self.buttonN_4.forget()
        self.buttonN_5.forget()
        self.buttonN_6.forget()
        self.buttonN_7.forget()
        self.buttonN_8.forget()
        self.buttonN_9.forget()
        self.buttonN_10.forget()
        self.buttonN_11.forget()
        self.buttonN_12.forget()
        self.buttonN_13.forget()
        self.buttonN_14.forget()
        self.buttonZ_1.forget()
        self.buttonZ_2.forget()
        self.buttonZ_3.forget()
        self.buttonZ_4.forget()
        self.buttonZ_5.forget()
        self.buttonZ_6.forget()
        self.buttonZ_7.forget()
        self.buttonZ_8.forget()
        self.buttonQ_1.forget()
        self.buttonQ_2.forget()
        self.buttonQ_3.forget()
        self.buttonQ_4.forget()
        self.buttonQ_5.forget()
        self.buttonQ_6.forget()
        self.buttonP_1.forget()
        self.buttonP_2.forget()
        self.buttonP_3.forget()
        self.buttonP_4.forget()
        self.buttonP_5.forget()
        self.buttonP_6.forget()
        self.buttonP_7.forget()
        self.buttonP_8.forget()
        self.buttonP_9.forget()
        self.buttonP_10.forget()
        self.buttonP_11.forget()
        self.buttonP_12.forget()
        self.buttonP_13.forget()
        self.buttonN.pack()
        self.buttonZ.pack()
        self.buttonQ.pack()
        self.buttonP.pack()



    def get_algN(self):
        self.buttonN.forget()
        self.buttonZ.forget()
        self.buttonQ.forget()
        self.buttonP.forget()
        self.buttonN_1.pack()
        self.buttonN_2.pack()
        self.buttonN_3.pack()
        self.buttonN_4.pack()
        self.buttonN_5.pack()
        self.buttonN_6.pack()
        self.buttonN_7.pack()
        self.buttonN_8.pack()
        self.buttonN_9.pack()
        self.buttonN_10.pack()
        self.buttonN_11.pack()
        self.buttonN_12.pack()
        self.buttonN_13.pack()
        self.buttonN_14.pack()
        self.buttonBA.pack(side = BOTTOM)



    def get_algZ(self):
        self.buttonN.forget()
        self.buttonZ.forget()
        self.buttonQ.forget()
        self.buttonP.forget()
        self.buttonZ_1.pack()
        self.buttonZ_2.pack()
        self.buttonZ_3.pack()
        self.buttonZ_4.pack()
        self.buttonZ_5.pack()
        self.buttonZ_6.pack()
        self.buttonZ_7.pack()
        self.buttonZ_8.pack()
        self.buttonBA.pack(side=BOTTOM)


    def get_algQ(self):
        self.buttonN.forget()
        self.buttonZ.forget()
        self.buttonQ.forget()
        self.buttonP.forget()
        self.buttonQ_1.pack()
        self.buttonQ_2.pack()
        self.buttonQ_3.pack()
        self.buttonQ_4.pack()
        self.buttonQ_5.pack()
        self.buttonQ_6.pack()
        self.buttonBA.pack(side=BOTTOM)


    def get_algP(self):
        self.buttonN.forget()
        self.buttonZ.forget()
        self.buttonQ.forget()
        self.buttonP.forget()
        self.buttonP_1.pack()
        self.buttonP_2.pack()
        self.buttonP_3.pack()
        self.buttonP_4.pack()
        self.buttonP_5.pack()
        self.buttonP_6.pack()
        self.buttonP_7.pack()
        self.buttonP_8.pack()
        self.buttonP_9.pack()
        self.buttonP_10.pack()
        self.buttonP_11.pack()
        self.buttonP_12.pack()
        self.buttonP_13.pack()
        self.buttonBA.pack(side=BOTTOM)


    def innumN1(self):
        global nn
        self.buttonN_1.forget()
        self.buttonN_2.forget()
        self.buttonN_3.forget()
        self.buttonN_4.forget()
        self.buttonN_5.forget()
        self.buttonN_6.forget()
        self.buttonN_7.forget()
        self.buttonN_8.forget()
        self.buttonN_9.forget()
        self.buttonN_10.forget()
        self.buttonN_11.forget()
        self.buttonN_12.forget()
        self.buttonN_13.forget()
        self.buttonN_14.forget()
        self.entryN1.pack()
        self.entryN2.pack()
        self.buttonREZ.pack()
        nn = 1

    def innumN2(self):
        global nn
        self.buttonN_1.forget()
        self.buttonN_2.forget()
        self.buttonN_3.forget()
        self.buttonN_4.forget()
        self.buttonN_5.forget()
        self.buttonN_6.forget()
        self.buttonN_7.forget()
        self.buttonN_8.forget()
        self.buttonN_9.forget()
        self.buttonN_10.forget()
        self.buttonN_11.forget()
        self.buttonN_12.forget()
        self.buttonN_13.forget()
        self.buttonN_14.forget()
        self.entryN1.pack()
        self.buttonREZ.pack()
        nn = 2

    def innumN3(self):
        global nn
        self.buttonN_1.forget()
        self.buttonN_2.forget()
        self.buttonN_3.forget()
        self.buttonN_4.forget()
        self.buttonN_5.forget()
        self.buttonN_6.forget()
        self.buttonN_7.forget()
        self.buttonN_8.forget()
        self.buttonN_9.forget()
        self.buttonN_10.forget()
        self.buttonN_11.forget()
        self.buttonN_12.forget()
        self.buttonN_13.forget()
        self.buttonN_14.forget()
        self.entryN1.pack()
        self.entryk.pack()
        self.buttonREZ.pack()
        nn = 3

    def innumN4(self):
        global nn
        self.buttonN_1.forget()
        self.buttonN_2.forget()
        self.buttonN_3.forget()
        self.buttonN_4.forget()
        self.buttonN_5.forget()
        self.buttonN_6.forget()
        self.buttonN_7.forget()
        self.buttonN_8.forget()
        self.buttonN_9.forget()
        self.buttonN_10.forget()
        self.buttonN_11.forget()
        self.buttonN_12.forget()
        self.buttonN_13.forget()
        self.buttonN_14.forget()
        self.entryN1.pack()
        self.entryN2.pack()
        self.buttonREZ.pack()
        nn = 4

    def innumN5(self):
        global nn
        self.buttonN_1.forget()
        self.buttonN_2.forget()
        self.buttonN_3.forget()
        self.buttonN_4.forget()
        self.buttonN_5.forget()
        self.buttonN_6.forget()
        self.buttonN_7.forget()
        self.buttonN_8.forget()
        self.buttonN_9.forget()
        self.buttonN_10.forget()
        self.buttonN_11.forget()
        self.buttonN_12.forget()
        self.buttonN_13.forget()
        self.buttonN_14.forget()
        self.entryN1.pack()
        self.entryN2.pack()
        self.buttonREZ.pack()
        nn = 5

    def innumN6(self):
        global nn
        self.buttonN_1.forget()
        self.buttonN_2.forget()
        self.buttonN_3.forget()
        self.buttonN_4.forget()
        self.buttonN_5.forget()
        self.buttonN_6.forget()
        self.buttonN_7.forget()
        self.buttonN_8.forget()
        self.buttonN_9.forget()
        self.buttonN_10.forget()
        self.buttonN_11.forget()
        self.buttonN_12.forget()
        self.buttonN_13.forget()
        self.buttonN_14.forget()
        self.entryN1.pack()
        self.entryN2.pack()
        self.buttonREZ.pack()
        nn = 6

    def innumN7(self):
        global nn
        self.buttonN_1.forget()
        self.buttonN_2.forget()
        self.buttonN_3.forget()
        self.buttonN_4.forget()
        self.buttonN_5.forget()
        self.buttonN_6.forget()
        self.buttonN_7.forget()
        self.buttonN_8.forget()
        self.buttonN_9.forget()
        self.buttonN_10.forget()
        self.buttonN_11.forget()
        self.buttonN_12.forget()
        self.buttonN_13.forget()
        self.buttonN_14.forget()
        self.entryN1.pack()
        self.entryk.pack()
        self.buttonREZ.pack()
        nn = 7

    def innumN8(self):
        global nn
        self.buttonN_1.forget()
        self.buttonN_2.forget()
        self.buttonN_3.forget()
        self.buttonN_4.forget()
        self.buttonN_5.forget()
        self.buttonN_6.forget()
        self.buttonN_7.forget()
        self.buttonN_8.forget()
        self.buttonN_9.forget()
        self.buttonN_10.forget()
        self.buttonN_11.forget()
        self.buttonN_12.forget()
        self.buttonN_13.forget()
        self.buttonN_14.forget()
        self.entryN1.pack()
        self.entryN2.pack()
        self.buttonREZ.pack()
        nn = 8

    def innumN9(self):
        global nn
        self.buttonN_1.forget()
        self.buttonN_2.forget()
        self.buttonN_3.forget()
        self.buttonN_4.forget()
        self.buttonN_5.forget()
        self.buttonN_6.forget()
        self.buttonN_7.forget()
        self.buttonN_8.forget()
        self.buttonN_9.forget()
        self.buttonN_10.forget()
        self.buttonN_11.forget()
        self.buttonN_12.forget()
        self.buttonN_13.forget()
        self.buttonN_14.forget()
        self.entryN1.pack()
        self.entryN2.pack()
        self.entryk.pack()
        self.buttonREZ.pack()
        nn = 9

    def innumN10(self):
        global nn
        self.buttonN_1.forget()
        self.buttonN_2.forget()
        self.buttonN_3.forget()
        self.buttonN_4.forget()
        self.buttonN_5.forget()
        self.buttonN_6.forget()
        self.buttonN_7.forget()
        self.buttonN_8.forget()
        self.buttonN_9.forget()
        self.buttonN_10.forget()
        self.buttonN_11.forget()
        self.buttonN_12.forget()
        self.buttonN_13.forget()
        self.buttonN_14.forget()
        self.entryN1.pack()
        self.entryN2.pack()
        self.buttonREZ.pack()
        nn = 10

    def innumN11(self):
        global nn
        self.buttonN_1.forget()
        self.buttonN_2.forget()
        self.buttonN_3.forget()
        self.buttonN_4.forget()
        self.buttonN_5.forget()
        self.buttonN_6.forget()
        self.buttonN_7.forget()
        self.buttonN_8.forget()
        self.buttonN_9.forget()
        self.buttonN_10.forget()
        self.buttonN_11.forget()
        self.buttonN_12.forget()
        self.buttonN_13.forget()
        self.buttonN_14.forget()
        self.entryN1.pack()
        self.entryN2.pack()
        self.buttonREZ.pack()
        nn = 11

    def innumN12(self):
        global nn
        self.buttonN_1.forget()
        self.buttonN_2.forget()
        self.buttonN_3.forget()
        self.buttonN_4.forget()
        self.buttonN_5.forget()
        self.buttonN_6.forget()
        self.buttonN_7.forget()
        self.buttonN_8.forget()
        self.buttonN_9.forget()
        self.buttonN_10.forget()
        self.buttonN_11.forget()
        self.buttonN_12.forget()
        self.buttonN_13.forget()
        self.buttonN_14.forget()
        self.entryN1.pack()
        self.entryN2.pack()
        self.buttonREZ.pack()
        nn = 12

    def innumN13(self):
        global nn
        self.buttonN_1.forget()
        self.buttonN_2.forget()
        self.buttonN_3.forget()
        self.buttonN_4.forget()
        self.buttonN_5.forget()
        self.buttonN_6.forget()
        self.buttonN_7.forget()
        self.buttonN_8.forget()
        self.buttonN_9.forget()
        self.buttonN_10.forget()
        self.buttonN_11.forget()
        self.buttonN_12.forget()
        self.buttonN_13.forget()
        self.buttonN_14.forget()
        self.entryN1.pack()
        self.entryN2.pack()
        self.buttonREZ.pack()
        nn = 13

    def innumN14(self):
        global nn
        self.buttonN_1.forget()
        self.buttonN_2.forget()
        self.buttonN_3.forget()
        self.buttonN_4.forget()
        self.buttonN_5.forget()
        self.buttonN_6.forget()
        self.buttonN_7.forget()
        self.buttonN_8.forget()
        self.buttonN_9.forget()
        self.buttonN_10.forget()
        self.buttonN_11.forget()
        self.buttonN_12.forget()
        self.buttonN_13.forget()
        self.buttonN_14.forget()
        self.entryN1.pack()
        self.entryN2.pack()
        self.buttonREZ.pack()
        nn = 14

    def innumZ1(self):
        global zz
        self.buttonZ_1.forget()
        self.buttonZ_2.forget()
        self.buttonZ_3.forget()
        self.buttonZ_4.forget()
        self.buttonZ_5.forget()
        self.buttonZ_6.forget()
        self.buttonZ_7.forget()
        self.buttonZ_8.forget()
        self.entryZ1.pack()
        self.buttonREZ.pack()
        zz = 1

    def innumZ2(self):
        global zz
        self.buttonZ_1.forget()
        self.buttonZ_2.forget()
        self.buttonZ_3.forget()
        self.buttonZ_4.forget()
        self.buttonZ_5.forget()
        self.buttonZ_6.forget()
        self.buttonZ_7.forget()
        self.buttonZ_8.forget()
        self.entryZ1.pack()
        self.buttonREZ.pack()
        zz = 2

    def innumZ3(self):
        global zz
        self.buttonZ_1.forget()
        self.buttonZ_2.forget()
        self.buttonZ_3.forget()
        self.buttonZ_4.forget()
        self.buttonZ_5.forget()
        self.buttonZ_6.forget()
        self.buttonZ_7.forget()
        self.buttonZ_8.forget()
        self.entryZ1.pack()
        self.buttonREZ.pack()
        zz = 3


    def innumZ4(self):
        global zz
        self.buttonZ_1.forget()
        self.buttonZ_2.forget()
        self.buttonZ_3.forget()
        self.buttonZ_4.forget()
        self.buttonZ_5.forget()
        self.buttonZ_6.forget()
        self.buttonZ_7.forget()
        self.buttonZ_8.forget()
        self.entryZ1.pack()
        self.entryZ2.pack()
        self.buttonREZ.pack()
        zz = 4

    def innumZ5(self):
        global zz
        self.buttonZ_1.forget()
        self.buttonZ_2.forget()
        self.buttonZ_3.forget()
        self.buttonZ_4.forget()
        self.buttonZ_5.forget()
        self.buttonZ_6.forget()
        self.buttonZ_7.forget()
        self.buttonZ_8.forget()
        self.entryZ1.pack()
        self.entryZ2.pack()
        self.buttonREZ.pack()
        zz = 5

    def innumZ6(self):
        global zz
        self.buttonZ_1.forget()
        self.buttonZ_2.forget()
        self.buttonZ_3.forget()
        self.buttonZ_4.forget()
        self.buttonZ_5.forget()
        self.buttonZ_6.forget()
        self.buttonZ_7.forget()
        self.buttonZ_8.forget()
        self.entryZ1.pack()
        self.entryZ2.pack()
        self.buttonREZ.pack()
        zz = 6

    def innumZ7(self):
        global zz
        self.buttonZ_1.forget()
        self.buttonZ_2.forget()
        self.buttonZ_3.forget()
        self.buttonZ_4.forget()
        self.buttonZ_5.forget()
        self.buttonZ_6.forget()
        self.buttonZ_7.forget()
        self.buttonZ_8.forget()
        self.entryZ1.pack()
        self.entryZ2.pack()
        self.buttonREZ.pack()
        zz = 7

    def innumZ8(self):
        global zz
        self.buttonZ_1.forget()
        self.buttonZ_2.forget()
        self.buttonZ_3.forget()
        self.buttonZ_4.forget()
        self.buttonZ_5.forget()
        self.buttonZ_6.forget()
        self.buttonZ_7.forget()
        self.buttonZ_8.forget()
        self.entryZ1.pack()
        self.entryZ2.pack()
        self.buttonREZ.pack()
        zz = 8

    def innumQ1(self):
        global qq
        self.buttonQ_1.forget()
        self.buttonQ_2.forget()
        self.buttonQ_3.forget()
        self.buttonQ_4.forget()
        self.buttonQ_5.forget()
        self.buttonQ_6.forget()
        self.entryQ1.pack()
        self.buttonREZ.pack()
        qq = 1

    def innumQ2(self):
        global qq
        self.buttonQ_1.forget()
        self.buttonQ_2.forget()
        self.buttonQ_3.forget()
        self.buttonQ_4.forget()
        self.buttonQ_5.forget()
        self.buttonQ_6.forget()
        self.entryQ1.pack()
        self.buttonREZ.pack()
        qq = 2

    def innumQ3(self):
        global qq
        self.buttonQ_1.forget()
        self.buttonQ_2.forget()
        self.buttonQ_3.forget()
        self.buttonQ_4.forget()
        self.buttonQ_5.forget()
        self.buttonQ_6.forget()
        self.entryQ1.pack()
        self.entryQ2.pack()
        self.buttonREZ.pack()
        qq = 3

    def innumQ4(self):
        global qq
        self.buttonQ_1.forget()
        self.buttonQ_2.forget()
        self.buttonQ_3.forget()
        self.buttonQ_4.forget()
        self.buttonQ_5.forget()
        self.buttonQ_6.forget()
        self.entryQ1.pack()
        self.entryQ2.pack()
        self.buttonREZ.pack()
        qq = 4

    def innumQ5(self):
        global qq
        self.buttonQ_1.forget()
        self.buttonQ_2.forget()
        self.buttonQ_3.forget()
        self.buttonQ_4.forget()
        self.buttonQ_5.forget()
        self.buttonQ_6.forget()
        self.entryQ1.pack()
        self.entryQ2.pack()
        self.buttonREZ.pack()
        qq = 5

    def innumQ6(self):
        global qq
        self.buttonQ_1.forget()
        self.buttonQ_2.forget()
        self.buttonQ_3.forget()
        self.buttonQ_4.forget()
        self.buttonQ_5.forget()
        self.buttonQ_6.forget()
        self.entryQ1.pack()
        self.entryQ2.pack()
        self.buttonREZ.pack()
        qq = 6

    def innumP1(self):
        global pp
        self.buttonP_1.forget()
        self.buttonP_2.forget()
        self.buttonP_3.forget()
        self.buttonP_4.forget()
        self.buttonP_5.forget()
        self.buttonP_6.forget()
        self.buttonP_7.forget()
        self.buttonP_8.forget()
        self.buttonP_9.forget()
        self.buttonP_10.forget()
        self.buttonP_11.forget()
        self.buttonP_12.forget()
        self.buttonP_13.forget()
        self.entryP1.pack()
        self.entryP2.pack()
        self.buttonREZ.pack()
        pp = 1

    def innumP2(self):
        global pp
        self.buttonP_1.forget()
        self.buttonP_2.forget()
        self.buttonP_3.forget()
        self.buttonP_4.forget()
        self.buttonP_5.forget()
        self.buttonP_6.forget()
        self.buttonP_7.forget()
        self.buttonP_8.forget()
        self.buttonP_9.forget()
        self.buttonP_10.forget()
        self.buttonP_11.forget()
        self.buttonP_12.forget()
        self.buttonP_13.forget()
        self.entryP1.pack()
        self.entryP2.pack()
        self.buttonREZ.pack()
        pp = 2

    def innumP3(self):
        global pp
        self.buttonP_1.forget()
        self.buttonP_2.forget()
        self.buttonP_3.forget()
        self.buttonP_4.forget()
        self.buttonP_5.forget()
        self.buttonP_6.forget()
        self.buttonP_7.forget()
        self.buttonP_8.forget()
        self.buttonP_9.forget()
        self.buttonP_10.forget()
        self.buttonP_11.forget()
        self.buttonP_12.forget()
        self.buttonP_13.forget()
        self.entryP1.pack()
        self.entryP2.pack()
        self.buttonREZ.pack()
        pp = 3

    def innumP4(self):
        global pp
        self.buttonP_1.forget()
        self.buttonP_2.forget()
        self.buttonP_3.forget()
        self.buttonP_4.forget()
        self.buttonP_5.forget()
        self.buttonP_6.forget()
        self.buttonP_7.forget()
        self.buttonP_8.forget()
        self.buttonP_9.forget()
        self.buttonP_10.forget()
        self.buttonP_11.forget()
        self.buttonP_12.forget()
        self.buttonP_13.forget()
        self.entryP1.pack()
        self.entryP2.pack()
        self.buttonREZ.pack()
        pp = 4

    def innumP5(self):
        global pp
        self.buttonP_1.forget()
        self.buttonP_2.forget()
        self.buttonP_3.forget()
        self.buttonP_4.forget()
        self.buttonP_5.forget()
        self.buttonP_6.forget()
        self.buttonP_7.forget()
        self.buttonP_8.forget()
        self.buttonP_9.forget()
        self.buttonP_10.forget()
        self.buttonP_11.forget()
        self.buttonP_12.forget()
        self.buttonP_13.forget()
        self.entryP1.pack()
        self.buttonREZ.pack()
        pp = 5

    def innumP6(self):
        global pp
        self.buttonP_1.forget()
        self.buttonP_2.forget()
        self.buttonP_3.forget()
        self.buttonP_4.forget()
        self.buttonP_5.forget()
        self.buttonP_6.forget()
        self.buttonP_7.forget()
        self.buttonP_8.forget()
        self.buttonP_9.forget()
        self.buttonP_10.forget()
        self.buttonP_11.forget()
        self.buttonP_12.forget()
        self.buttonP_13.forget()
        self.entryP1.pack()
        self.buttonREZ.pack()
        pp = 6

    def innumP7(self):
        global pp
        self.buttonP_1.forget()
        self.buttonP_2.forget()
        self.buttonP_3.forget()
        self.buttonP_4.forget()
        self.buttonP_5.forget()
        self.buttonP_6.forget()
        self.buttonP_7.forget()
        self.buttonP_8.forget()
        self.buttonP_9.forget()
        self.buttonP_10.forget()
        self.buttonP_11.forget()
        self.buttonP_12.forget()
        self.buttonP_13.forget()
        self.entryP1.pack()
        self.buttonREZ.pack()
        pp = 7

    def innumP8(self):
        global pp
        self.buttonP_1.forget()
        self.buttonP_2.forget()
        self.buttonP_3.forget()
        self.buttonP_4.forget()
        self.buttonP_5.forget()
        self.buttonP_6.forget()
        self.buttonP_7.forget()
        self.buttonP_8.forget()
        self.buttonP_9.forget()
        self.buttonP_10.forget()
        self.buttonP_11.forget()
        self.buttonP_12.forget()
        self.buttonP_13.forget()
        self.entryP1.pack()
        self.entryP2.pack()
        self.buttonREZ.pack()
        pp = 8

    def innumP9(self):
        global pp
        self.buttonP_1.forget()
        self.buttonP_2.forget()
        self.buttonP_3.forget()
        self.buttonP_4.forget()
        self.buttonP_5.forget()
        self.buttonP_6.forget()
        self.buttonP_7.forget()
        self.buttonP_8.forget()
        self.buttonP_9.forget()
        self.buttonP_10.forget()
        self.buttonP_11.forget()
        self.buttonP_12.forget()
        self.buttonP_13.forget()
        self.entryP1.pack()
        self.entryP2.pack()
        self.buttonREZ.pack()
        pp = 9

    def innumP10(self):
        global pp
        self.buttonP_1.forget()
        self.buttonP_2.forget()
        self.buttonP_3.forget()
        self.buttonP_4.forget()
        self.buttonP_5.forget()
        self.buttonP_6.forget()
        self.buttonP_7.forget()
        self.buttonP_8.forget()
        self.buttonP_9.forget()
        self.buttonP_10.forget()
        self.buttonP_11.forget()
        self.buttonP_12.forget()
        self.buttonP_13.forget()
        self.entryP1.pack()
        self.entryP2.pack()
        self.buttonREZ.pack()
        pp = 10

    def innumP11(self):
        global pp
        self.buttonP_1.forget()
        self.buttonP_2.forget()
        self.buttonP_3.forget()
        self.buttonP_4.forget()
        self.buttonP_5.forget()
        self.buttonP_6.forget()
        self.buttonP_7.forget()
        self.buttonP_8.forget()
        self.buttonP_9.forget()
        self.buttonP_10.forget()
        self.buttonP_11.forget()
        self.buttonP_12.forget()
        self.buttonP_13.forget()
        self.entryP1.pack()
        self.entryP2.pack()
        self.buttonREZ.pack()
        pp = 11

    def innumP12(self):
        global pp
        self.buttonP_1.forget()
        self.buttonP_2.forget()
        self.buttonP_3.forget()
        self.buttonP_4.forget()
        self.buttonP_5.forget()
        self.buttonP_6.forget()
        self.buttonP_7.forget()
        self.buttonP_8.forget()
        self.buttonP_9.forget()
        self.buttonP_10.forget()
        self.buttonP_11.forget()
        self.buttonP_12.forget()
        self.buttonP_13.forget()
        self.entryP1.pack()
        self.buttonREZ.pack()
        pp = 12

    def innumP13(self):
        global pp
        self.buttonP_1.forget()
        self.buttonP_2.forget()
        self.buttonP_3.forget()
        self.buttonP_4.forget()
        self.buttonP_5.forget()
        self.buttonP_6.forget()
        self.buttonP_7.forget()
        self.buttonP_8.forget()
        self.buttonP_9.forget()
        self.buttonP_10.forget()
        self.buttonP_11.forget()
        self.buttonP_12.forget()
        self.buttonP_13.forget()
        self.entryP1.pack()
        self.buttonREZ.pack()
        pp = 13

    def zoutput(self):
        global zz, nn, qq, pp
        if zz == 1:
            self.buttonREZ.forget()
            z = self.entryZ1.get()
            z1 = integers(z)
            self.entryZ1.delete(0, 'end')
            self.entryZ1.forget()
            otv = ABS_Z_N(z1)
            self.l1.config(text=otv)
            self.l1.pack()
        elif zz == 2:
            self.buttonREZ.forget()
            z = self.entryZ1.get()
            z1 = integers(z)
            self.entryZ1.delete(0, 'end')
            self.entryZ1.forget()
            otv = POZ_Z_D(z1)
            self.l1.config(text=otv)
            self.l1.pack()
        elif zz == 3:
            self.buttonREZ.forget()
            z = self.entryZ1.get()
            z1 = integers(z)
            self.entryZ1.delete(0, 'end')
            self.entryZ1.forget()
            otv = MUL_ZM_Z(z1)
            self.l1.config(text=otv)
            self.l1.pack()
        elif zz == 4:
            self.buttonREZ.forget()
            z = self.entryZ1.get()
            z1 = integers(z)
            self.entryZ1.delete(0, 'end')
            self.entryZ1.forget()
            z = self.entryZ2.get()
            z2 = integers(z)
            self.entryZ2.delete(0, 'end')
            self.entryZ2.forget()
            otv = ADD_ZZ_Z(z1, z2)
            self.l1.config(text=otv)
            self.l1.pack()
        elif zz == 5:
            self.buttonREZ.forget()
            z = self.entryZ1.get()
            z1 = integers(z)
            self.entryZ1.delete(0, 'end')
            self.entryZ1.forget()
            z = self.entryZ2.get()
            z2 = integers(z)
            self.entryZ2.delete(0, 'end')
            self.entryZ2.forget()
            otv = SUB_ZZ_Z(z1, z2)
            self.l1.config(text=otv)
            self.l1.pack()
        elif zz == 6:
            self.buttonREZ.forget()
            z = self.entryZ1.get()
            z1 = integers(z)
            self.entryZ1.delete(0, 'end')
            self.entryZ1.forget()
            z = self.entryZ2.get()
            z2 = integers(z)
            self.entryZ2.delete(0, 'end')
            self.entryZ2.forget()
            otv = MUL_ZZ_Z(z1, z2)
            self.l1.config(text=otv)
            self.l1.pack()
        elif zz == 7:
            self.buttonREZ.forget()
            z = self.entryZ1.get()
            z1 = integers(z)
            self.entryZ1.delete(0, 'end')
            self.entryZ1.forget()
            z = self.entryZ2.get()
            z2 = integers(z)
            self.entryZ2.delete(0, 'end')
            self.entryZ2.forget()
            otv = DIV_ZZ_Z(z1, z2)
            self.l1.config(text=otv)
            self.l1.pack()
        elif zz == 8:
            self.buttonREZ.forget()
            z = self.entryZ1.get()
            z1 = integers(z)
            self.entryZ1.delete(0, 'end')
            self.entryZ1.forget()
            z = self.entryZ2.get()
            z2 = integers(z)
            self.entryZ2.delete(0, 'end')
            self.entryZ2.forget()
            otv = MOD_ZZ_Z(z1, z2)
            self.l1.config(text=otv)
            self.l1.pack()
        elif nn == 1:
            self.buttonREZ.forget()
            n = self.entryN1.get()
            n1 = natural(n)
            self.entryN1.delete(0, 'end')
            self.entryN1.forget()
            n = self.entryN2.get()
            n2 = natural(n)
            self.entryN2.delete(0, 'end')
            self.entryN2.forget()
            otv = COM_NN_D(n1, n2)
            self.l1.config(text=otv)
            self.l1.pack()
        elif nn == 2:
            self.buttonREZ.forget()
            n = self.entryN1.get()
            n1 = natural(n)
            self.entryN1.delete(0, 'end')
            self.entryN1.forget()
            otv = NZER_N_B(n1)
            self.l1.config(text=otv)
            self.l1.pack()
        elif nn == 3:
            self.buttonREZ.forget()
            n = self.entryN1.get()
            n1 = natural(n)
            self.entryN1.delete(0, 'end')
            self.entryN1.forget()
            otv = ADD_1N_N(n1)
            self.l1.config(text=otv)
            self.l1.pack()
        elif nn == 4:
            self.buttonREZ.forget()
            n = self.entryN1.get()
            n1 = natural(n)
            self.entryN1.delete(0, 'end')
            self.entryN1.forget()
            n = self.entryN2.get()
            n2 = natural(n)
            self.entryN2.delete(0, 'end')
            self.entryN2.forget()
            otv = ADD_NN_N(n1, n2)
            self.l1.config(text=otv)
            self.l1.pack()
        elif nn == 5:
            self.buttonREZ.forget()
            n = self.entryN1.get()
            n1 = natural(n)
            self.entryN1.delete(0, 'end')
            self.entryN1.forget()
            n = self.entryN2.get()
            n2 = natural(n)
            self.entryN2.delete(0, 'end')
            self.entryN2.forget()
            otv = SUB_NN_N(n1, n2)
            self.l1.config(text=otv)
            self.l1.pack()
        elif nn == 6:
            self.buttonREZ.forget()
            n = self.entryN1.get()
            n1 = natural(n)
            self.entryN1.delete(0, 'end')
            self.entryN1.forget()
            n2 = int(self.entryN2.get())
            self.entryN2.delete(0, 'end')
            self.entryN2.forget()
            otv = MUL_ND_N(n1, n2)
            self.l1.config(text=otv)
            self.l1.pack()
        elif nn == 7:
            self.buttonREZ.forget()
            n = self.entryN1.get()
            n1 = natural(n)
            self.entryN1.delete(0, 'end')
            self.entryN1.forget()
            k = int(self.entryk.get())
            self.entryk.delete(0, 'end')
            self.entryk.forget()
            otv = MUL_Nk_N(n1,k)
            self.l1.config(text=otv)
            self.l1.pack()
        elif nn == 8:
            self.buttonREZ.forget()
            n = self.entryN1.get()
            n1 = natural(n)
            self.entryN1.delete(0, 'end')
            self.entryN1.forget()
            n = self.entryN2.get()
            n2 = natural(n)
            self.entryN2.delete(0, 'end')
            self.entryN2.forget()
            otv = MUL_NN_N(n1,n2)
            self.l1.config(text=otv)
            self.l1.pack()
        elif nn == 9:
            self.buttonREZ.forget()
            n = self.entryN1.get()
            n1 = natural(n)
            self.entryN1.delete(0, 'end')
            self.entryN1.forget()
            n = self.entryN2.get()
            n2 = natural(n)
            self.entryN2.delete(0, 'end')
            self.entryN2.forget()
            k1 = self.entryk.get()
            k = natural(k1)
            self.entryk.delete(0, 'end')
            self.entryk.forget()
            otv = SUB_NDN_N(n1, n2, k)
            self.l1.config(text=otv)
            self.l1.pack()
        elif nn == 10:
            self.buttonREZ.forget()
            n = self.entryN1.get()
            n1 = natural(n)
            self.entryN1.delete(0, 'end')
            self.entryN1.forget()
            n = self.entryN2.get()
            n2 = natural(n)
            self.entryN2.delete(0, 'end')
            self.entryN2.forget()
            otv = DIV_NN_Dk(n1, n2)
            self.l1.config(text=otv)
            self.l1.pack()
        elif nn == 11:
            self.buttonREZ.forget()
            n = self.entryN1.get()
            n1 = natural(n)
            self.entryN1.delete(0, 'end')
            self.entryN1.forget()
            n = self.entryN2.get()
            n2 = natural(n)
            self.entryN2.delete(0, 'end')
            self.entryN2.forget()
            otv = DIV_NN_N(n1,n2)
            self.l1.config(text=otv)
            self.l1.pack()
        elif nn == 12:
            self.buttonREZ.forget()
            n = self.entryN1.get()
            n1 = natural(n)
            self.entryN1.delete(0, 'end')
            self.entryN1.forget()
            n = self.entryN2.get()
            n2 = natural(n)
            self.entryN2.delete(0, 'end')
            self.entryN2.forget()
            otv = MOD_NN_N(n1,n2)
            self.l1.config(text=otv)
            self.l1.pack()
        elif nn == 13:
            self.buttonREZ.forget()
            n = self.entryN1.get()
            n1 = natural(n)
            self.entryN1.delete(0, 'end')
            self.entryN1.forget()
            n = self.entryN2.get()
            n2 = natural(n)
            self.entryN2.delete(0, 'end')
            self.entryN2.forget()
            otv =GCF_NN_N(n1, n2)
            self.l1.config(text=otv)
            self.l1.pack()
        elif nn == 14:
            self.buttonREZ.forget()
            n = self.entryN1.get()
            n1 = natural(n)
            self.entryN1.delete(0, 'end')
            self.entryN1.forget()
            n = self.entryN2.get()
            n2 = natural(n)
            self.entryN2.delete(0, 'end')
            self.entryN2.forget()
            otv = LCM_NN_N(n1, n2)
            self.l1.config(text=otv)
            self.l1.pack()
        elif qq == 1:
            self.buttonREZ.forget()
            q = self.entryQ1.get()
            q1 = rational(integers(q.split("/")[0]), natural(q.split("/")[1]))
            self.entryQ1.delete(0, 'end')
            self.entryQ1.forget()
            otv = RED_Q_Q(q1)
            self.l1.config(text=otv)
            self.l1.pack()
        elif qq == 2:
            self.buttonREZ.forget()
            q = self.entryQ1.get()
            q1 = rational(integers(q.split("/")[0]), natural(q.split("/")[1]))
            self.entryQ1.delete(0, 'end')
            self.entryQ1.forget()
            otv = INT_Q_B(q1)
            self.l1.config(text=otv)
            self.l1.pack()
        elif qq == 3:
            self.buttonREZ.forget()
            q = self.entryQ1.get()
            q1 =  rational(integers(q.split("/")[0]), natural(q.split("/")[1]))
            self.entryQ1.delete(0, 'end')
            self.entryQ1.forget()
            q = self.entryQ2.get()
            q2 =  rational(integers(q.split("/")[0]), natural(q.split("/")[1]))
            self.entryQ2.delete(0, 'end')
            self.entryQ2.forget()
            otv = ADD_QQ_Q(q1, q2)
            self.l1.config(text=otv)
            self.l1.pack()
        elif qq == 4:
            self.buttonREZ.forget()
            q = self.entryQ1.get()
            q1 =  rational(integers(q.split("/")[0]), natural(q.split("/")[1]))
            self.entryQ1.delete(0, 'end')
            self.entryQ1.forget()
            q = self.entryQ2.get()
            q2 =  rational(integers(q.split("/")[0]), natural(q.split("/")[1]))
            self.entryQ2.delete(0, 'end')
            self.entryQ2.forget()
            otv = SUB_QQ_Q(q1, q2)
            self.l1.config(text=otv)
            self.l1.pack()
        elif qq == 5:
            self.buttonREZ.forget()
            q = self.entryQ1.get()
            q1 =  rational(integers(q.split("/")[0]), natural(q.split("/")[1]))
            self.entryQ1.delete(0, 'end')
            self.entryQ1.forget()
            q = self.entryQ2.get()
            q2 = rational(integers(q.split("/")[0]), natural(q.split("/")[1]))
            self.entryQ2.delete(0, 'end')
            self.entryQ2.forget()
            otv = MUL_QQ_Q(q1, q2)
            self.l1.config(text=otv)
            self.l1.pack()
        elif qq == 6:
            self.buttonREZ.forget()
            q = self.entryQ1.get()
            q1 = rational(integers(q.split("/")[0]), natural(q.split("/")[1]))
            self.entryQ1.delete(0, 'end')
            self.entryQ1.forget()
            q = self.entryQ2.get()
            q2 = rational(integers(q.split("/")[0]), natural(q.split("/")[1]))
            self.entryQ2.delete(0, 'end')
            self.entryQ2.forget()
            otv = DIV_QQ_Q(q1, q2)
            self.l1.config(text=otv)
            self.l1.pack()
        elif pp == 1:
            self.buttonREZ.forget()
            p = self.entryP1.get()
            p1 = [rational(integers(i.split("/")[0]), natural(i.split("/")[1])) if '/' in i else rational(integers(i)) for i in p.split()]
            a = polynom(p1)
            self.entryP1.delete(0, 'end')
            self.entryP1.forget()
            p = self.entryP2.get()
            p2 = [rational(integers(i.split("/")[0]), natural(i.split("/")[1])) if '/' in i else rational(integers(i)) for i in p.split()]
            b = polynom(p2)
            self.entryP2.delete(0, 'end')
            self.entryP2.forget()
            otv = ADD_PP_P(a, b)
            self.l1.config(text=otv)
            self.l1.pack()
        elif pp == 2:
            self.buttonREZ.forget()
            p = self.entryP1.get()
            p1 = [rational(integers(i.split("/")[0]), natural(i.split("/")[1])) if '/' in i else rational(integers(i)) for i in p.split()]
            a = polynom(p1)
            self.entryP1.delete(0, 'end')
            self.entryP1.forget()
            p = self.entryP2.get()
            p2 = [rational(integers(i.split("/")[0]), natural(i.split("/")[1])) if '/' in i else rational(integers(i)) for i in p.split()]
            b = polynom(p2)
            self.entryP2.delete(0, 'end')
            self.entryP2.forget()
            otv = SUB_PP_P(a, b)
            self.l1.config(text=otv)
            self.l1.pack()
        elif pp == 3:
            self.buttonREZ.forget()
            p = self.entryP1.get()
            p1 = [rational(integers(i.split("/")[0]), natural(i.split("/")[1])) if '/' in i else rational(integers(i)) for i in p.split()]
            a = polynom(p1)
            self.entryP1.delete(0, 'end')
            self.entryP1.forget()
            q = self.entryP2.get()
            x = rational(integers(q.split("/")[0]), natural(q.split("/")[1]))
            self.entryP2.delete(0, 'end')
            self.entryP2.forget()
            otv = MUL_PQ_P(a, x)
            self.l1.config(text=otv)
            self.l1.pack()
        elif pp == 4:
            self.buttonREZ.forget()
            p = self.entryP1.get()
            p1 = [rational(integers(i.split("/")[0]), natural(i.split("/")[1])) if '/' in i else rational(integers(i)) for i in p.split()]
            a = polynom(p1)
            self.entryP1.delete(0, 'end')
            self.entryP1.forget()
            k = int(self.entryP2.get())
            self.entryP2.delete(0, 'end')
            self.entryP2.forget()
            otv = MUL_Pxk_P(a, k)
            self.l1.config(text=otv)
            self.l1.pack()
        elif pp == 5:
            self.buttonREZ.forget()
            p = self.entryP1.get()
            p1 = [rational(integers(i.split("/")[0]), natural(i.split("/")[1])) if '/' in i else rational(integers(i)) for i in p.split()]
            a = polynom(p1)
            self.entryP1.delete(0, 'end')
            self.entryP1.forget()
            otv =  LED_P_Q(a)
            self.l1.config(text=otv)
            self.l1.pack()
        elif pp == 6:
            self.buttonREZ.forget()
            p = self.entryP1.get()
            p1 = [rational(integers(i.split("/")[0]), natural(i.split("/")[1])) if '/' in i else rational(integers(i)) for i in p.split()]
            a = polynom(p1)
            self.entryP1.delete(0, 'end')
            self.entryP1.forget()
            otv = DEG_P_N(a)
            self.l1.config(text=otv)
            self.l1.pack()
        elif pp == 7:
            self.buttonREZ.forget()
            p = self.entryP1.get()
            p1 = [rational(integers(i.split("/")[0]), natural(i.split("/")[1])) if '/' in i else rational(integers(i)) for i in p.split()]
            a = polynom(p1)
            self.entryP1.delete(0, 'end')
            self.entryP1.forget()
            otv = FAC_P_Q(a)
            self.l1.config(text=otv)
            self.l1.pack()
        elif pp == 8:
            self.buttonREZ.forget()
            p = self.entryP1.get()
            p1 = [rational(integers(i.split("/")[0]), natural(i.split("/")[1])) if '/' in i else rational(integers(i)) for i in p.split()]
            a = polynom(p1)
            self.entryP1.delete(0, 'end')
            self.entryP1.forget()
            p = self.entryP2.get()
            p2 = [rational(integers(i.split("/")[0]), natural(i.split("/")[1])) if '/' in i else rational(integers(i)) for i in p.split()]
            b = polynom(p2)
            self.entryP2.delete(0, 'end')
            self.entryP2.forget()
            otv = MUL_PP_P(a, b)
            self.l1.config(text=otv)
            self.l1.pack()
        elif pp == 9:
            self.buttonREZ.forget()
            p = self.entryP1.get()
            p1 = [rational(integers(i.split("/")[0]), natural(i.split("/")[1])) if '/' in i else rational(integers(i)) for i in p.split()]
            a = polynom(p1)
            self.entryP1.delete(0, 'end')
            self.entryP1.forget()
            p = self.entryP2.get()
            p2 = [rational(integers(i.split("/")[0]), natural(i.split("/")[1])) if '/' in i else rational(integers(i)) for i in p.split()]
            b = polynom(p2)
            self.entryP2.delete(0, 'end')
            self.entryP2.forget()
            otv = DIV_PP_P(a, b)
            self.l1.config(text=otv)
            self.l1.pack()
        elif pp == 10:
            self.buttonREZ.forget()
            p = self.entryP1.get()
            p1 = [rational(integers(i.split("/")[0]), natural(i.split("/")[1])) if '/' in i else rational(integers(i)) for i in p.split()]
            a = polynom(p1)
            self.entryP1.delete(0, 'end')
            self.entryP1.forget()
            p = self.entryP2.get()
            p2 = [rational(integers(i.split("/")[0]), natural(i.split("/")[1])) if '/' in i else rational(integers(i)) for i in p.split()]
            b = polynom(p2)
            self.entryP2.delete(0, 'end')
            self.entryP2.forget()
            otv = MOD_PP_P(a, b)
            self.l1.config(text=otv)
            self.l1.pack()
        elif pp == 11:
            self.buttonREZ.forget()
            p = self.entryP1.get()
            p1 = [rational(integers(i.split("/")[0]), natural(i.split("/")[1])) if '/' in i else rational(integers(i)) for i in p.split()]
            a = polynom(p1)
            self.entryP1.delete(0, 'end')
            self.entryP1.forget()
            p = self.entryP2.get()
            p2 = [rational(integers(i.split("/")[0]), natural(i.split("/")[1])) if '/' in i else rational(integers(i)) for i in p.split()]
            b = polynom(p2)
            self.entryP2.delete(0, 'end')
            self.entryP2.forget()
            otv = GCF_PP_P(a, b)
            self.l1.config(text=otv)
            self.l1.pack()
        elif pp == 12:
            self.buttonREZ.forget()
            p = self.entryP1.get()
            p1 = [rational(integers(i.split("/")[0]), natural(i.split("/")[1])) if '/' in i else rational(integers(i)) for i in p.split()]
            a = polynom(p1)
            self.entryP1.delete(0, 'end')
            self.entryP1.forget()
            otv =  DER_P_P(a)
            self.l1.config(text=otv)
            self.l1.pack()
        elif pp == 13:
            self.buttonREZ.forget()
            p = self.entryP1.get()
            p1 = [rational(integers(i.split("/")[0]), natural(i.split("/")[1])) if '/' in i else rational(integers(i)) for i in p.split()]
            a = polynom(p1)
            self.entryP1.delete(0, 'end')
            self.entryP1.forget()
            otv = NMR_P_P(a)
            self.l1.config(text=otv)
            self.l1.pack()










def input_naturals():
  s = input("Введите цифру:")
  a = natural(s)
  st1 = input("Введите первое число:")
  st2 = input("Введите второе число:")
  n1 = natural(st1)
  n2 = natural(st2)
  return 0

def input_integers():
 str0 = input("Введите первое число со знаком + или -:")
 z1 = integers(str0)
 str01 = input("Введите второе число со знаком + или -:")
 z2 = integers(str01)
 return 0




if __name__ == "__main__":
    window = Window(810, 675, "Калькулятор")
    window.run()